name: Bug Report
description: Report a problem with the mod
title: "[BUG] "
labels: [ bug ]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the problem you encountered.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Explain how to reproduce the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Mod Version
      description: Which version are you using?
    validations:
      required: true
